apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podconfigmapcontroller-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["myapi.mydomain.com"]
    resources: ["podconfigmaprules"]
    verbs: ["get", "list", "watch"]
